"use client";

import React, { createContext, useContext, useEffect, useState } from "react";

export type SupportedLanguage = "en" | "hi" | "mr" | "bn" | "ta" | "te";

export interface LanguageMeta {
  code: SupportedLanguage;
  name: string;
  nativeName: string;
  speechCode: string;
}

export const LANGUAGES: LanguageMeta[] = [
  { code: "en", name: "English", nativeName: "English", speechCode: "en-IN" },
  { code: "hi", name: "Hindi", nativeName: "हिंदी", speechCode: "hi-IN" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", speechCode: "mr-IN" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", speechCode: "bn-IN" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", speechCode: "ta-IN" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", speechCode: "te-IN" },
];

const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    govOfIndia: "Government of India",
    ministry: "Ministry of Housing and Urban Affairs",
    digitalPublicGood: "National Digital Public Good",
    appName: "JanSetu AI",
    tagline: "AI-Powered Citizen Grievance & Public Service Platform",
    subtitle: "Turning everyday civic complaints into structured, actionable municipal work orders using Google Gemini.",
    reportProblem: "Report a Civic Problem",
    trackStatus: "Track Complaint Status",
    citizenPortal: "Citizen Portal",
    adminPortal: "Admin Desk",
    dashboard: "Citizen Dashboard",
    publicTracker: "Public Registry",
    home: "Home",
    reportIssue: "Report Issue",
    login: "Sign In",
    register: "Register",
    logout: "Log Out",
    voiceInput: "Voice Input",
    listening: "Listening... Speak in your language",
    stopListening: "Stop Recording",
    describeIssue: "Describe your civic grievance in your own words...",
    enterLocation: "Enter locality, landmark, ward or street address...",
    detectLocation: "Detect My Location",
    analyzingAI: "Analyzing grievance with Gemini AI...",
    confirmSubmit: "Confirm & Submit Work Order",
    category: "Category",
    priority: "Priority",
    department: "Assigned Department",
    status: "Status",
    reported: "Reported",
    assigned: "Assigned",
    inProgress: "In Progress",
    resolved: "Resolved",
    critical: "Critical",
    high: "High",
    medium: "Medium",
    low: "Low",
    roads: "Roads & Infrastructure",
    water: "Water Supply & Sewerage",
    sanitation: "Solid Waste & Sanitation",
    electricity: "Power Distribution",
    streetlight: "Public Lighting",
    drainage: "Stormwater Drainage",
    publicSafety: "Public Safety & Hazards",
    other: "General Municipal Civic",
    recentComplaints: "Recent Civic Grievances",
    nationalData: "National Open Data Intelligence",
    dataGov: "data.gov.in Integration",
    isroBhuvan: "ISRO / Bhuvan Geospatial",
    imdWeather: "IMD Meteorological Alerts",
    whoHealth: "WHO & Urban Health Data",
    emergencyHelpline: "Emergency Helpline 1913 / 112",
  },
  hi: {
    govOfIndia: "भारत सरकार",
    ministry: "आवासन और शहरी कार्य मंत्रालय",
    digitalPublicGood: "राष्ट्रीय डिजिटल पब्लिक गुड",
    appName: "जनसेतु एआई",
    tagline: "एआई-संचालित नागरिक शिकायत एवं जनसेवा मंच",
    subtitle: "गूगल जेमिनी एआई द्वारा आम बोलचाल की शिकायतों को संरचित नगर निगम कार्य आदेशों में बदलें।",
    reportProblem: "नागरिक समस्या दर्ज करें",
    trackStatus: "शिकायत की स्थिति जांचें",
    citizenPortal: "नागरिक पोर्टल",
    adminPortal: "अधिकारी डेस्क",
    dashboard: "नागरिक डैशबोर्ड",
    publicTracker: "सार्वजनिक रजिस्ट्री",
    home: "होम",
    reportIssue: "समस्या दर्ज करें",
    login: "लॉग इन",
    register: "पंजीकरण",
    logout: "लॉग आउट",
    voiceInput: "ध्वनि इनपुट (बोलकर बताएं)",
    listening: "सुन रहे हैं... अपनी भाषा में बोलें",
    stopListening: "रिकॉर्डिंग रोकें",
    describeIssue: "अपनी नागरिक शिकायत को अपने शब्दों में बताएं...",
    enterLocation: "क्षेत्र, लैंडमार्क, वार्ड या सड़क का पता दर्ज करें...",
    detectLocation: "मेरा स्थान पहचानें",
    analyzingAI: "जेमिनी एआई द्वारा विश्लेषण जारी है...",
    confirmSubmit: "पुष्टि करें और शिकायत जमा करें",
    category: "श्रेणी",
    priority: "प्राथमिकता",
    department: "संबंधित विभाग",
    status: "स्थिति",
    reported: "दर्ज की गई",
    assigned: "विभाग को सौंपी",
    inProgress: "कार्य प्रगति पर",
    resolved: "समाधान संपन्न",
    critical: "अति गंभीर (आपातकालीन)",
    high: "उच्च प्राथमिकता",
    medium: "मध्यम",
    low: "सामान्य",
    roads: "सड़क एवं आधारभूत संरचना",
    water: "जलापूर्ति एवं सीवरेज",
    sanitation: "ठोस अपशिष्ट एवं स्वच्छता",
    electricity: "विद्युत वितरण",
    streetlight: "स्ट्रीटलाइट एवं सार्वजनिक प्रकाश",
    drainage: "नाली एवं जल निकासी",
    publicSafety: "सार्वजनिक सुरक्षा",
    other: "अन्य नागरिक सेवाएं",
    recentComplaints: "हालिया नागरिक शिकायतें",
    nationalData: "राष्ट्रीय ओपन डेटा इंटेलिजेंस",
    dataGov: "data.gov.in एकीकरण",
    isroBhuvan: "इसरो / भुवन उपग्रह डेटा",
    imdWeather: "मौसम विभाग (IMD) चेतावनी",
    whoHealth: "विश्व स्वास्थ्य संगठन (WHO) डेटा",
    emergencyHelpline: "नागरिक हेल्पलाइन 1913 / 112",
  },
  mr: {
    govOfIndia: "भारत सरकार",
    ministry: "गृहनिर्माण आणि नगर व्यवहार मंत्रालय",
    digitalPublicGood: "राष्ट्रीय डिजिटल पब्लिक गुड",
    appName: "जनसेतू एआय",
    tagline: "एआय-सक्षम नागरिक तक्रार आणि लोकसेवा प्रणाली",
    subtitle: "सामान्य भाषेतील तक्रारींचे गुगल जेमिनीद्वारे महानगरपालिका कार्य आदेशात रूपांतर.",
    reportProblem: "नागरी तक्रार नोंदवा",
    trackStatus: "तक्रार स्थिती तपासा",
    citizenPortal: "नागरिक पोर्टल",
    adminPortal: "अधिकारी डेस्क",
    dashboard: "नागरिक डॅशबोर्ड",
    publicTracker: "सार्वजनिक नोंदवही",
    home: "मुख्यपृष्ठ",
    reportIssue: "तक्रार नोंदवा",
    login: "लॉग इन",
    register: "नोंदणी करा",
    logout: "लॉग आउट",
    voiceInput: "आवाज इनपुट (बोला)",
    listening: "ऐकत आहे... आपल्या भाषेत बोला",
    stopListening: "थांबवा",
    describeIssue: "आपली नागरी समस्या स्वतःच्या शब्दांत सांगा...",
    enterLocation: "परिसर, वॉर्ड किंवा पत्ता प्रविष्ट करा...",
    detectLocation: "माझे स्थान शोधा",
    analyzingAI: "जेमिनी एआय द्वारे विश्लेषण सुरू आहे...",
    confirmSubmit: "तक्रार निश्चित करा व पाठवा",
    category: "वर्गवारी",
    priority: "प्राधान्य",
    department: "संबंधित विभाग",
    status: "स्थिती",
    reported: "नोंद झाली",
    assigned: "नेमणूक झाली",
    inProgress: "काम सुरू आहे",
    resolved: "निवारण पूर्ण",
    critical: "अति तातडीचे",
    high: "उच्च",
    medium: "मध्यम",
    low: "सामान्य",
    roads: "रस्ते व पायाभूत सुविधा",
    water: "पाणीपुरवठा व मलनिस्सारण",
    sanitation: "कचरा व्यवस्थापन व स्वच्छता",
    electricity: "विद्युत पुरवठा",
    streetlight: "सार्वजनिक दिवे",
    drainage: "ड्रेनेज व जलवाहिन्या",
    publicSafety: "सार्वजनिक सुरक्षा",
    other: "इतर नागरी समस्या",
    recentComplaints: "ताज्या नागरिक तक्रारी",
    nationalData: "राष्ट्रीय ओपन डेटा बुद्धिमत्ता",
    dataGov: "data.gov.in एकत्रीकरण",
    isroBhuvan: "इस्रो / भुवन उपग्रह नकाशा",
    imdWeather: "हवामान विभाग (IMD) सूचना",
    whoHealth: "आरोग्य निर्देशांक",
    emergencyHelpline: "महानगरपालिका हेल्पलाइन 1913 / 112",
  },
  bn: {
    govOfIndia: "ভারত সরকার",
    ministry: "আবাসন ও নগর বিষয়ক মন্ত্রক",
    digitalPublicGood: "জাতীয় ডিজিটাল পাবলিক গুড",
    appName: "জনসেতু এআই",
    tagline: "এআই-চালিত নাগরিক অভিযোগ ও জনসেবা প্ল্যাটফর্ম",
    subtitle: "দৈনন্দিন নাগরিক সমস্যাগুলি গুগল জেমিনির মাধ্যমে কার্যকরী পৌরসভা নির্দেশে রূপান্তর করুন।",
    reportProblem: "সমস্যা রিপোর্ট করুন",
    trackStatus: "অভিযোগের স্থিতি দেখুন",
    citizenPortal: "নাগরিক পোর্টাল",
    adminPortal: "প্রশাসনিক ডেস্ক",
    dashboard: "নাগরিক ড্যাশবোর্ড",
    publicTracker: "জনসাধারণের রেজিস্ট্রি",
    home: "হোম",
    reportIssue: "অভিযোগ জানান",
    login: "লগ ইন",
    register: "নিবন্ধন",
    logout: "লগ আউট",
    voiceInput: "ভয়েস ইনপুট (বলুন)",
    listening: "শুনছি... আপনার ভাষায় কথা বলুন",
    stopListening: "রেকর্ডিং থামান",
    describeIssue: "আপনার অভিযোগ নিজের ভাষায় বর্ণনা করুন...",
    enterLocation: "এলাকা, ল্যান্ডমার্ক বা ওয়ার্ড নম্বর লিখুন...",
    detectLocation: "অবস্থান সনাক্ত করুন",
    analyzingAI: "জেমিনি এআই বিশ্লেষণ করছে...",
    confirmSubmit: "নিশ্চিত করুন ও জমা দিন",
    category: "বিভাগ",
    priority: "অগ্রাধিকার",
    department: "দায়িত্বপ্রাপ্ত দপ্তর",
    status: "অবস্থা",
    reported: "নথিবদ্ধ",
    assigned: "দায়িত্বপ্রাপ্ত",
    inProgress: "কাজ চলছে",
    resolved: "সমাধান হয়েছে",
    critical: "জরুরি",
    high: "উচ্চ",
    medium: "মাঝারি",
    low: "সাধারণ",
    roads: "রাস্তা ও অবকাঠামো",
    water: "জল সরবরাহ ও নিষ্কাশন",
    sanitation: "বর্জ্য ও পরিচ্ছন্নতা",
    electricity: "বিদ্যুৎ সরবরাহ",
    streetlight: "পথবাতি",
    drainage: "নিকাশি নালা",
    publicSafety: "জননিরাপত্তা",
    other: "অন্যান্য নাগরিক সেবা",
    recentComplaints: "সাম্প্রতিক অভিযোগ",
    nationalData: "জাতীয় ওপেন ডেটা ইন্টেলিজেন্স",
    dataGov: "data.gov.in ইন্টিগ্রেশন",
    isroBhuvan: "ইসরো / ভুবন উপগ্রহ ডেটা",
    imdWeather: "আবহাওয়া দপ্তর সতর্কতা",
    whoHealth: "স্বাস্থ্য পরিসংখ্যান",
    emergencyHelpline: "পৌরসভা হেল্পলাইন ১৯১৩ / ১১২",
  },
  ta: {
    govOfIndia: "இந்திய அரசு",
    ministry: "வீட்டுவசதி மற்றும் நகர்ப்புற விவகாரங்கள் அமைச்சகம்",
    digitalPublicGood: "தேசிய டிஜிட்டல் பொது நன்மை",
    appName: "ஜன்சேது ஏஐ",
    tagline: "ஏஐ-இயங்கும் குடிமக்கள் குறைதீர்ப்பு மற்றும் பொது சேவை தளம்",
    subtitle: "கூகுள் ஜெமினி மூலம் அன்றாட குடிமக்கள் புகார்களை நகராட்சி பணி ஆணைகளாக மாற்றுதல்.",
    reportProblem: "குறைபாடு பதிவு செய்",
    trackStatus: "புகார் நிலையை அறியவும்",
    citizenPortal: "குடிமக்கள் போர்டல்",
    adminPortal: "நிர்வாக மேசை",
    dashboard: "குடிமக்கள் டாஷ்போர்டு",
    publicTracker: "பொது பதிவேடு",
    home: "முகப்பு",
    reportIssue: "புகார் பதிவு",
    login: "உள்நுழை",
    register: "பதிவு செய்க",
    logout: "வெளியேறு",
    voiceInput: "குரல் பதிவு (பேசவும்)",
    listening: "கேட்கிறது... உங்கள் மொழியில் பேசவும்",
    stopListening: "நிறுத்து",
    describeIssue: "உங்கள் புகாரை உங்கள் சொந்த வார்த்தைகளில் விவரிக்கவும்...",
    enterLocation: "பகுதி, வார்டு அல்லது முகவரியை உள்ளிடவும்...",
    detectLocation: "இருப்பிடத்தைக் கண்டறி",
    analyzingAI: "ஜெமினி ஏஐ பகுப்பாய்வு செய்கிறது...",
    confirmSubmit: "உறுதிசெய்து சமர்ப்பிக்கவும்",
    category: "பிரிவு",
    priority: "முன்னுரிமை",
    department: "துறை",
    status: "நிலை",
    reported: "பதிவு செய்யப்பட்டது",
    assigned: "ஒதுக்கப்பட்டது",
    inProgress: "செயலில் உள்ளது",
    resolved: "தீர்க்கப்பட்டது",
    critical: "மிக அவசரம்",
    high: "உயர் முன்னுரிமை",
    medium: "நடுத்தரம்",
    low: "குறைவு",
    roads: "சாலைகள் மற்றும் உள்கட்டமைப்பு",
    water: "குடிநீர் மற்றும் கழிவுநீர்",
    sanitation: "திடக்கழிவு மேலாண்மை",
    electricity: "மின்சார விநியோகம்",
    streetlight: "தெரு விளக்குகள்",
    drainage: "மழைநீர் வடிகால்",
    publicSafety: "பொது பாதுகாப்பு",
    other: "இதர நகராட்சி சேவைகள்",
    recentComplaints: "சமீபத்திய புகார்கள்",
    nationalData: "தேசிய திறந்த தரவு நுண்ணறிவு",
    dataGov: "data.gov.in இணைப்பு",
    isroBhuvan: "இஸ்ரோ / புவன் செயற்கைக்கோள் தரவு",
    imdWeather: "வானிலை ஆய்வு மைய எச்சரிக்கை",
    whoHealth: "சுகாதார குறியீடுகள்",
    emergencyHelpline: "அவசர உதவி எண் 1913 / 112",
  },
  te: {
    govOfIndia: "భారత ప్రభుత్వం",
    ministry: "గృహనిర్మాణ మరియు పట్టణ వ్యవహారాల మంత్రిత్వ శాఖ",
    digitalPublicGood: "జాతీయ డిజిటల్ పబ్లిక్ గూడ్",
    appName: "జనసేతు ఏఐ",
    tagline: "ఏఐ ఆధారిత పౌర ఫిర్యాదులు మరియు ప్రజా సేవల వేదిక",
    subtitle: "గూగుల్ జెమిని ద్వారా సాధారణ పౌర సమస్యలను అధికారిక మునిసిపల్ వర్క్ ఆర్డర్‌లుగా మార్చండి.",
    reportProblem: "సమస్యను నివేదించండి",
    trackStatus: "ఫిర్యాదు స్థితి తెలుసుకోండి",
    citizenPortal: "పౌర పోర్టల్",
    adminPortal: "అధికార డెస్క్",
    dashboard: "పౌర డ్యాష్‌బోర్డ్",
    publicTracker: "ప్రజా రిజిస్ట్రీ",
    home: "హోమ్",
    reportIssue: "సమస్య నమోదు",
    login: "లాగిన్",
    register: "రిజిస్టర్",
    logout: "లాగ్ అవుట్",
    voiceInput: "వాయిస్ ఇన్‌పుట్ (మాట్లాడండి)",
    listening: "వింటోంది... మీ భాషలో మాట్లాడండి",
    stopListening: "ఆపండి",
    describeIssue: "మీ సమస్యను మీ స్వంత మాటల్లో వివరించండి...",
    enterLocation: "ప్రాంతం, ల్యాండ్‌మార్క్ లేదా వార్డు చిరునామా నమోదు చేయండి...",
    detectLocation: "నా స్థానాన్ని గుర్తించండి",
    analyzingAI: "జెమిని ఏఐ విశ్లేషిస్తోంది...",
    confirmSubmit: "ధృవీకరించి సమర్పించండి",
    category: "వర్గం",
    priority: "ప్రాధాన్యత",
    department: "సంబంధిత శాఖ",
    status: "స్థితి",
    reported: "నమోదైంది",
    assigned: "కేటాయించబడింది",
    inProgress: "పురోగతిలో ఉంది",
    resolved: "పరిష్కరించబడింది",
    critical: "అత్యవసరం",
    high: "అధిక ప్రాధాన్యత",
    medium: "మధ్యస్థం",
    low: "సాధారణం",
    roads: "రోడ్లు మరియు మౌలిక వసతులు",
    water: "మంచినీరు మరియు డ్రైనేజీ",
    sanitation: "పారిశుద్ధ్యం మరియు చెత్త సేకరణ",
    electricity: "విద్యుత్ సరఫరా",
    streetlight: "వీధి దీపాలు",
    drainage: "మురుగునీటి కాలువలు",
    publicSafety: "ప్రజా భద్రత",
    other: "ఇతర పౌర సమస్యలు",
    recentComplaints: "ఇటీవలి ఫిర్యాదులు",
    nationalData: "జాతీయ ఓపెన్ డేటా ఇంటెలిజెన్స్",
    dataGov: "data.gov.in అనుసంధానం",
    isroBhuvan: "ఇస్రో / భువన్ ఉపగ్రహ డేటా",
    imdWeather: "వాతావరణ శాఖ (IMD) హెచ్చరికలు",
    whoHealth: "ఆరోగ్య సూచికలు",
    emergencyHelpline: "మున్సిపల్ హెల్ప్‌లైన్ 1913 / 112",
  },
};

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
  currentLangMeta: LanguageMeta;
  languages: LanguageMeta[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<SupportedLanguage>("en");

  useEffect(() => {
    const saved = localStorage.getItem("jansetu_lang") as SupportedLanguage | null;
    if (saved && TRANSLATIONS[saved]) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: SupportedLanguage) => {
    setLanguageState(lang);
    localStorage.setItem("jansetu_lang", lang);
  };

  const t = (key: string): string => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.en[key] || key;
  };

  const currentLangMeta =
    LANGUAGES.find((l) => l.code === language) || LANGUAGES[0];

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        currentLangMeta,
        languages: LANGUAGES,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      language: "en" as SupportedLanguage,
      setLanguage: () => {},
      t: (key: string) => key,
      currentLangMeta: LANGUAGES[0],
      languages: LANGUAGES,
    };
  }
  return context;
}
